### ISSUE TITLE
Sell car

### ISSUE THREAD

**Issue by Arcon3** [greeksamp/Greek-Roleplay-Script#100]
Θα προτεινα οπως και στο προηγουμενο version του παιχνιδιου να μπορουμε με καποιον τροπο να πουλαμε τα αμαξια μας στον σερβερ σε στην περιπτωση που δεν τα θελει κανενας

**Comment by greeksamp-souvlaki** [comment]
Δεν θα γίνει κάτι τέτοιο αυτή τη στιγμή. Μπορείς να δώσεις το αυτοκίνητο σε έναν δεύτερο λογαριασμό σου.
