### ISSUE TITLE
Gangs

### ISSUE THREAD

**Issue by Arcon3** [greeksamp/Greek-Roleplay-Script#101]
Ειναι αρκετα να πω εδω... Πρωτα απο ολα τα Gang members και ειδικα ο Leader να εχουνε καποια συγκεκριμενα Skins αναλογα με το gang τα οποια θα μπορουμε να αλλαζουμε στην ``βαση`` εκει που ειναι το Gang. Δευτερον Gang ranks.... το gang να εχει καποια ρανκς (ρανκ 1, ρανκ 2) για το καθε ατομο με αυτο μπορουμε να βαλουμε συγκεκριμενο σκιν για καθε ατομο αλλα και συγκεκριμενα ΟΠΛΑ.... Θεωρω οτι το καθε ατομο αναλογα με το ρανκ του να μπορει να κανει spawn me ta opla tou ωστε αμα γινει καποιο ``Gang war`` να μην χρειαζετε να αδειασει ολα του τα λεφτα σε Ammunations

**Comment by Thanasis358** [comment]
Όταν γίνεται gang war οι gang members παίρνουν αυτόματα, από τον σέρβερ, όπλα και armor.

**Comment by Arcon3** [comment]
Μπορει να αλλαξε μετα το update

**Comment by greeksamp-souvlaki** [comment]
Το αναφέρω στο wiki, τα όπλα θα υπάρχουν την ώρα του Gang War.

Το άλλο με τα Skins μπορεί να το αποφασίσει ο αρχηγός και να το επιβάλλει στα μέλη του.
