### ISSUE TITLE
Sell Car / Buy Car / Vehicle Locations Unknown - BUG

### ISSUE THREAD

**Issue by Storiel008** [greeksamp/Greek-Roleplay-Script#102]
Βρήκα πάλι bug, αυτήν την φορά με το Sell Car και με τα Vehicle Locations. 

1. Από το παλιό σέρβερ είχα ήδη 5 cars, και τώρα έχοντας Premium αγόρασα άλλα 3, με σύνολο 8 cars. Αποφάσισα να πουλήσω ένα απο τα παλία μου και για κάποιον λόγο μόλις τελείωσε η πώληση ξανφικά η θέση στην οποία ήταν το συγκεκριμένο car στο Vehicle Locations άλλαξε απο "Sabre (car)" σε **"Unknown", με Location στο Blueberry.**
2. Τα Vehicle Locations έχουν **9 car slots**, ενώ το όριο του κάθε παίκτη ειναι 8.
3. Αφόυ πούλησα το car μου και μετά είχα 7 cars, πήγα να αγοράσω ένα άλλο και **μου είπε το σέρβερ πως έχω ήδη 8 cars, κάτι που δέν ισχύει.**

Πιστεύω πρέπει να φτιαχτεί άμεσα γιατί κάποιος που μπορεί να πλήρωσε για το Premium δεν θα μπορεί να έχει 8 cars, και για άλλους σημαντικούς λόγους.

Screenshots:
https://imgur.com/a/A99JLjB

EDIT: Μετά απο Relog, για κάποιον λόγο μου δείχνει πως πάλι έχω το αμάξι που πούλησα, και εξαφανίστηκαν τα 9 Slots στο Vehicle Locations. Αυτό είναι άλλο Bug απο μόνο του γιατί ακόμα έχω το Sabre που πούλησα, αλλά πήρα και τα λεφτά της πώλησης.

EDIT 2: Ξαναπούλησα το Sabre και αυτήν την φορά είχα όντως 7 αμάξια οπότε πήρα το 8ο αμάξι που ήθελα να πάρω τόση ώρα. Μετά απο Relog όμως, το Sabre ΞΑΝΑΕΠΈΣΤΡΕΨΕ σε εμένα και τώρα εχω.. 9 αμαξια..? Αλήθεια δεν ξέρω τι γίνεται με το Bug.

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ, διορθώθηκε.

Το αυτοκίνητο μεταφέρθηκε στον Thanasis358.
