### ISSUE TITLE
/Goto -BUG

### ISSUE THREAD

**Issue by Arcon3** [greeksamp/Greek-Roleplay-Script#103]
Καποιες φoρες αμα πας να κανεις teleport στον αλλον με /goto γινετε αυτο που θα δειξω στο screenshot και δεν μπορεις να κανεις τιποτα παρα relog

Screenshot:  https://imgur.com/a/wrWC5ZB
![sa-mp-033](https://user-images.githubusercontent.com/86049183/174117857-d2d4b4c4-ae84-47b1-906a-a8847059c6df.png)

**Comment by Thanasis358** [comment]
Είναι bug του GTA αυτό
Με relog φτιάχνεται.

**Comment by greeksamp-souvlaki** [comment]
Ναι θα διορθωθεί κάτι εκεί.

Να μειωθεί η χρήση του goto όμως.
