### ISSUE TITLE
Car Park - BUG

### ISSUE THREAD

**Issue by Storiel008** [greeksamp/Greek-Roleplay-Script#104]
Πολύ απλά το Park δεν δουλεύει. Φαίνεται σαν να δουλέυει όταν το χρησιμοποιεί κάποιος, αλλά όταν έρθει η ώρα να κάνει Respawn το αμάξι εμφανίζεται εκεί που έκανε Spawn για πρώτη φορα. (Είτε εκεί που το αγόρασες είτε εκεί που το έκανες /park στην Season 1)

**Comment by Arcon3** [comment]
Κατι τετοιο σε εμενα προσωπικα δεν εγινε καθως εκανα ολα τα αμαξια μου παρκ σε αλλο μερος και κανουνε spawn κανονικα στο νεο μερος

**Comment by greeksamp-souvlaki** [comment]
Μπορείς να γυρίσεις ένα βίντεο με ένα παράδειγμα γιατί δεν βλέπω κάποιο πρόβλημα αυτή τη στιγμή.

**Comment by Storiel008** [comment]
Φυσικά, αλλά ξαναλέω πως απλά κανω Park ένα αμάξι κάπου και μετά απο Relog δεν βρήσκεται εκει. Μόλις μπω θα τραβήξω ένα βίντεο.

**Comment by Storiel008** [comment]
Από ότι φαίνεται το πρόβλημα φτιάχτηκε από μόνο του, οπότε κλείνω το Issue.
