### ISSUE TITLE
Bar Drinking Animation - BUG

### ISSUE THREAD

**Issue by Thanasis358** [greeksamp/Greek-Roleplay-Script#105]
Βρήκα ένα bug, όταν πας σε ένα bar και επιλέγεις ποτό από το menu, ο χαρακτήρας αντί να κάνει το drinking animation κάνει το pee animation. Αυτό συμβαίνει σε όλα τα ποτά και bar.

Video Example: https://youtu.be/qZwGWnDrwJg (το video ήταν full πρόχειρο, για αυτό έχει χαμηλά fps)

**Comment by greeksamp-souvlaki** [comment]
Το αναφέρω στο wiki, αν πιεις περισσότερο από ό,τι χρειάζεται, ο παίκτης θα κάνει αυτό το animation.

Είναι εντάξει.
