### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by Arcon3** [greeksamp/Greek-Roleplay-Script#106]
Καλό θα ήταν να μπουν και άλλα skins καθώς είναι λίγο περιορισμενα θα έλεγα

**Comment by greeksamp-souvlaki** [comment]
Όλα τα διαθέσιμα Skins είναι στο παιχνίδι.
Ανάλογα με το τι δουλειά κάνεις ή σε ποια συμμορία είσαι η επιλογή είναι περιορισμένη.
Το αναφέρω στο wiki.
