### ISSUE TITLE
Bug στο trucking company ls

### ISSUE THREAD

**Issue by aleksis22YT** [greeksamp/Greek-Roleplay-Script#109]
Όταν πάω να δουλέψω στο select route διαλέγω το trailer στο ocean docks. Παω να πάρω το trailer και οταν το παίρνω το checkpoint δεν αλλάζει απο εκεί που παίρνεις το trailer με αποτέλεσμα να μπορείς να μεταφέρεις το trailer στο ίδιο checkpoint όπου το πήρες και έτσι είναι απεριόριστα λεφτά.

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ, διορθώθηκε.

Δοκίμασε το και αν υπάρχει ακόμα θέμα, στείλε μου πάλι.
