### ISSUE TITLE
Elegy is not acceptable into Wheels Arch Angels

### ISSUE THREAD

**Issue by Storiel008** [greeksamp/Greek-Roleplay-Script#112]
![image](https://user-images.githubusercontent.com/85932078/178157344-2c42e1e5-cd0e-428e-984f-9c2371f8c836.png)

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ, διορθώθηκε.

Αν εμφανιστεί πάλι πρόβλημα, άνοιξε πάλι ένα issue.
