### ISSUE TITLE
|Server Down|

### ISSUE THREAD

**Issue by Thanasis358** [greeksamp/Greek-Roleplay-Script#117]
Ο server είναι down, new update??? (i hope)
![server down](https://github.com/greeksamp/Greek-Roleplay-Script/assets/84641518/e4ee8a4a-72de-4a19-8b2a-d42918c6f141)

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ, πρέπει να λειτουργεί πάλι 😶‍🌫️
