### ISSUE TITLE
Wanted Level Bug

### ISSUE THREAD

**Issue by Storiel008** [greeksamp/Greek-Roleplay-Script#20]
Όταν κάποιος παίκτης είναι Wanted, υπάρχουν 2 πιθανά προβλήματα που μπορεί να υπάρξουν. 
1. Το Wanted Level μένει σταθερό, εκτός αν ο πάικτης κάνει relog. (Το οποίο δεν φτιάχνει πάντα το πρόβλημα)
2. Το Wanted Level κατεβαίνει, όμως κατεβαίνει πάρα πολύ αργά. Και όταν δεν υπάρχουν αστυνομικοί στο σέρβερ, αυτό είναι πρόβλημα.

**Comment by greeksamp-souvlaki** [comment]
Δεν μπορώ να εντοπίσω το πρόβλημα εύκολα.

Θα κάνουμε κάτι άλλο όμως, θα δείχνουμε πόσος χρόνος απομένει για το wanted level.
Ίσως τότε βρούμε και το πρόβλημα που αναφέρεις.

https://github.com/greeksamp/Greek-Roleplay-Script/issues/26

**Comment by greeksamp-souvlaki** [comment]
Λύθηκε με το Pull Request https://github.com/greeksamp/Greek-Roleplay-Script/pull/47
