### ISSUE TITLE
Get Payday Score after Disconnect

### ISSUE THREAD

**Issue by Storiel008** [greeksamp/Greek-Roleplay-Script#41]
Ένα πρόβλημα που έχω εγώ ο ίδιος, και μερικά άλλα μέλη του community, έιναι να γινόμαστε disconnected απο το σερβερ (για τον οποιονδήποτε λογο), με αποτέλεσμα να μην παίρνουμε score/λεφτά. 

Ένας καλός τρόπος να το αποφύγουμε αυτό είναι το σέρβερ να αποθηκεύει πόσα λεπτά παίξαμε στο τελευταίο μας session, ώστε όταν ξαναμπούμε να πάρουμε το score και τα λεφτά που χάσαμε.

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ! Δεν θα έλεγα ότι είναι bug, απλά το είχαμε σκεφτεί έτσι ώστε μόνο ο χρόνος σε ένα session (20 λεπτά) θα μετράει.

Μπορούμε όμως να το συνδυάσουμε, έτσι ώστε να αποθηκεύεται ο συνολικός χρόνος από το τελευταίο payday του παίκτη.
