### ISSUE TITLE
Φτιάξτε ένα bug με την πισινα

### ISSUE THREAD

**Issue by kardiolohtipos07** [greeksamp/Greek-Roleplay-Script#42]
Σήμερα αγόρασα ένα σπίτι στον σέρβερ που είναι στην παραλία για 60.000 €. Πρόσεξα όμως ότι το σπίτι ενώ έχει πισίνα δεν έχει νερό. Ρώτησα και μου είπαν ότι είναι bug , μπορεί ν φτιαχτεί;

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ! Δεν νομίζω, πολύ πιθανόν να μην υπάρχει γενικά νερό σε αυτή την πισίνα.
Συμβαίνει γενικότερα στον χάρτη αυτό, άρα δεν είναι bug.

Μπορούμε όμως να κοιτάξουμε να βάλουμε το object 10444 εκεί πέρα, εάν ταιριάζει.
Θα το δούμε σαν προσθήκη.

**Comment by kardiolohtipos07** [comment]
Ωραία άμα μπορείτε βάλτε νερο

**Comment by greeksamp-souvlaki** [comment]
Δεν γίνεται ούτε με το 10444, ούτε με τα 19603, 19604.

Ακόμη και αν μπουν πολλές φορές τα object του 19603 δεν θα λειτουργεί σαν κανονική πισίνα.
Είναι παράληψη παιχνιδιού, λείπει η θάλασσα όπως υπάρχει για παράδειγμα στην πισίνα του V-Rock Hotel.
