### ISSUE TITLE
Βάλτε αν μπορείτε στο /radio και το δικό μου ραδιόφωνο.

### ISSUE THREAD

**Issue by kostaspapoutsisweb** [greeksamp/Greek-Roleplay-Script#43]
Έχω ένα web radio και σκεφτόμουν πως θα ήταν καλή ιδέα να εμπλουτιστεί το custom radio των οχημάτων και με αυτό. Αφήνω το main stream link εδώ για να κάνετε το setup αν εγκριθεί το suggest! http://stream.zeno.fm/5ye7xw94tk8uv Σαν όνομα βάλτε Papoutsis Radio!

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ! Ναι μπορούμε να το προσθέσουμε.
