### ISSUE TITLE
Προσθήκη τραπεζιτών

### ISSUE THREAD

**Issue by kardiolohtipos07** [greeksamp/Greek-Roleplay-Script#46]
Βάλτε τραπεζίτες που όταν κάνεις /rob να σηκώνουν τα χέρια ψηλά. Επίσης θα πρότεινα να μπει δουλειά στρατού .

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ! Αυτό με τους τραπεζίτες έχει μπει ήδη στο επόμενο update.

Για την δουλειά στρατού φτιάξε νέο issue και περιέγραψε πως ακριβώς το σκέφτεσαι.

**Comment by greeksamp-souvlaki** [comment]
Duplicate https://github.com/greeksamp/Greek-Roleplay-Script/issues/29
