### ISSUE TITLE
Player Disconnect Bug

### ISSUE THREAD

**Issue by Storiel008** [greeksamp/Greek-Roleplay-Script#48]
Αν ένας παίκτης δεν έχει πρόσβαση στο ίντερνετ την ώρα που παίζει στο σέρβερ, και γίνει disconnected, όταν ξαναφορτόσει ξαφνικά θα του βγάλει ένα Register Screen, το οποίο αν ολοκληρωθεί, ο παίκτης θα spawnάρει στο σέρβερ σαν καινούριος.
(Αυτό φτιάχνεται με relog)

Screenshots από το Bug :
https://imgur.com/646DaaB
https://imgur.com/cCvjFvU

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ, δεν είναι bug του server.

Όταν για κάποιο λόγο κάνεις reconnect, συνδέεσαι πλέον με το όνομα [BCC]STORIEL000 και όχι με το STORIEL000.
Θα πρέπει να βγεις από το παιχνίδι για να συνδεθείς με το κανονικό όνομα του λογαριασμού σου, χωρίς το tag της Clan σου.
