### ISSUE TITLE
Wrong Special Action for /pee

### ISSUE THREAD

**Issue by Storiel008** [greeksamp/Greek-Roleplay-Script#49]
Το command /pee χρησιμοποιεί λάθος Special Action, με αποτέλεσμα να σηκώνει τα χέρια του ο παίκτης μετά απο χρήση το Command.

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ, ναι ισχύει δεν αποθηκεύτηκε σωστά η εντολή.
