### ISSUE TITLE
aleksis22_YT radio

### ISSUE THREAD

**Issue by aleksis22YT** [greeksamp/Greek-Roleplay-Script#53]
Αν γίνεται θα ήθελα πολύ να βάλετε εφόσον το έχουν ζητήσει κάποιοι παίχτες το ράδιο μου που περιέχει rap και trap μουσική. Όνομα θα ήθελα να έχει aleksis22_YT radio . Το URL είναι αυτό : http://stream.zeno.fm/fp1w7s2gmy8uv

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ! Θα προστεθεί!
