### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by aleksis22YT** [greeksamp/Greek-Roleplay-Script#58]
Όταν είσαι συνοδηγός σε ένα αμάξι η μία μηχανή μπορείς να ανοιγοκλείνεις φώτα να ανοιγοκλείνεις το αμάξι εάν βρίσκεσαι σε μηχανή μπορείς να την κλείσεις και αυτή

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ! Ναι πρέπει να διορθωθεί.
