### ISSUE TITLE
samp corona 

### ISSUE THREAD

**Issue by steveGR121** [greeksamp/Greek-Roleplay-Script#60]
εχω μια ιδεα αλλα οχι και τοσο καλη λεω να μπορουμε αν νοικιαζουμε σπιτια σε καθε ατομο γιατι εμενα μου ζητσουσαν αμα μπορουμε να νοικιασουε σπιτια οποτε πιστευω οτι θα βοηθηση βεβαια με πληρωμη και νοικιο ξερω γω κανα 500 ευρω καπου εκει

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ! Ναι θα μπορούσε να φτιαχτεί κάτι τέτοιο, αν και τα σπίτια για τον αριθμό των παικτών που έχουμε είναι αρκετά.

**Comment by greeksamp-souvlaki** [comment]
Έχει υλοποιηθεί με το καινούργιο update.

Μόλις το δοκιμάσεις, άνοιξε καινούργιο issue αν έχεις να προτείνεις κάτι άλλο.
