### ISSUE TITLE
Bug στο pee

### ISSUE THREAD

**Issue by aleksis22YT** [greeksamp/Greek-Roleplay-Script#63]
Όταν κάνεις /pee και μετά /animstop συνεχίζει ο παίχτης ενώ περπατάει να κατουραει. Φώτο : https://photos.app.goo.gl/eZoZPdUwE2379RpV9

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ! Έτσι είναι από το παιχνίδι.
Γράφει το μήνυμα ότι πρέπει να πατήσεις και το ENTER για να σταματήσει το special action.
