### ISSUE TITLE
Suggestion Idea

### ISSUE THREAD

**Issue by stamatis3** [greeksamp/Greek-Roleplay-Script#66]
Voice chat in game

**Comment by aleksis22YT** [comment]
@stamatis3 το samp δεν υποστηρίζει voice chat

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ!

Μάλλον εννοείς αυτό https://github.com/CyberMor/sampvoice

Δεν υποστηρίζεται επίσημα το plugin που κυκλοφορεί και από δοκιμές που έχω κάνει, είναι ασταθές.
Δεν θα πρότεινα ούτε στους παίκτες να το εγκαταστήσουν.

Περιμένουμε το https://open.mp/ αν φτιάξουν κάτι αυτοί, το οποίο φαίνεται δύσκολο.
Μπορείς να χρησιμοποιήσεις το discord ή το chat. Μην συγκρίνετε το παιχνίδι με το GTA V.
