### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by aleksis22YT** [greeksamp/Greek-Roleplay-Script#67]
Όταν μπαίνεις να φτιάξεις το αμάξι σου σε pay n spray η σε άλλο μαγαζί δεν σου κρατάει λεφτά.

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ! Έτσι λειτουργούν τα PayNSpray στο SAMP. Χρειάζεται παρ' όλα αυτά να έχεις τα χρήματα πριν μπεις μέσα.

Είναι στο πλάνο να κλείσουν όλα αυτά τα καταστήματα και να γίνουν ιδιωτικά όπως παλιά, που εκεί πλέον θα υπάρχει τιμή εισόδου.
