### ISSUE TITLE
Bug στο σύστημα με το jail

### ISSUE THREAD

**Issue by kostaspapoutsisweb** [greeksamp/Greek-Roleplay-Script#7]
Σήμερα είδα πως με τα Materials κάποιος που είναι jailed μπορεί να πουλήσει σε συγκρατούμενό του όπλα. Το αναφέρω επειδή το θεωρώ Bug και το θεωρώ Bug επειδή θεωρητικά οι κρατούμενοι δεν έχουν αγοραπωλησίες όπλων. Αν δεν είναι Bug και πρέπει να είναι έτσι ο μηχανισμός του game απλά αγνοείστε το.

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ, όντως δεν είναι σωστό.

Θεωρητικά οι αστυνομικοί μπορούν να κάνουν **/frisk** και **/confiscate**.

Πρέπει να λυθεί.
