### ISSUE TITLE
New MarkellMTB Radio Fix (2021 works 100%)

### ISSUE THREAD

**Issue by MarkelPercussion** [greeksamp/Greek-Roleplay-Script#72]
http://stream.zeno.fm/etawvyh7py8uv

pragmatika ama de doulepsei tha autoktonisw.

**Comment by Thanasis358** [comment]
Δουλεύει μόλις το δοκίμασα στο VLC.

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ! Θα το ενημερώσω.
