### ISSUE TITLE
music

### ISSUE THREAD

**Issue by steveGR121** [greeksamp/Greek-Roleplay-Script#76]
να μπορουμε να ακουμε τραγουδια και εξ απο το αμαξι

**Comment by greeksamp-souvlaki** [comment]
https://github.com/greeksamp/Greek-Roleplay-Script/issues/75

**Comment by greeksamp-souvlaki** [comment]
Κλείνει προς το παρόν, μιας και το #75 εκκρεμεί ακόμη.
Ευχαριστώ!
