### ISSUE TITLE
Να παραμένει το rank από κάποιο faction εάν φύγεις

### ISSUE THREAD

**Issue by kardiolohtipos07** [greeksamp/Greek-Roleplay-Script#78]
Προτείνω σε περίπτωση που είμαι γιατρός και για παράδειγμα πάω και γίνω αστυνόμος και μετά επιστρέψω στο γιατρος να συνεχίσω απτό ίδιο rank

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ για την ιδέα! Αυτό όμως δεν θα αλλάξει προς το παρόν.
Μόλις φεύγεις από κάποια δουλειά, όλη η πρόοδος σου μηδενίζεται γιατί τα υπόλοιπα μέλη συνεχίζουν να μένουν και να διεκδικούν καλύτερες θέσεις.

Παρ' όλα αυτά, στο πάνελ και στο ιστορικό σου θα φαίνονται όλα για κάποιον αρχηγό που θέλει να δει που ήσουν παλιά.

Αν έχεις κάποια άλλη πρόταση μόλις δοκιμάσεις το νέο σύστημα, άνοιξε καινούργιο issue.
