### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by stamatis3** [greeksamp/Greek-Roleplay-Script#80]
Στο login αν γίνετε το spawn να μετακινηθεί γιατί δεν μπορώ να μπω στον server bugari με το hitman

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ! Μπορείς να στείλεις κάποιο βίντεο ή να δείξεις που ακριβώς spawnάρεις;
Δεν μπορώ να καταλάβω ακριβώς ποιο είναι το πρόβλημα.

**Comment by stamatis3** [comment]
Έστειλα στο discord σας ο stamatis#8221 είμαι

Στις Κυρ, 18 Ιουλ 2021, 11:35 π.μ. ο χρήστης Souvlaki <
***@***.***> έγραψε:

**Comment by greeksamp-souvlaki** [comment]
Το πρόβλημα έχει ήδη λυθεί.
Θα ανεβεί με το καινούργιο update.
