### ISSUE TITLE
Souvlaki

### ISSUE THREAD

**Issue by basilis04** [greeksamp/Greek-Roleplay-Script#82]
Αδελφε πρεπει να γυρισεις πισω στον server

**Comment by kostaspapoutsisweb** [comment]
Φίλε εδώ είναι για αναφορές bugs που εντοπίζονται στον server και προτάσεις για το τι να μπει και όχι να τσατάρουμε με κάθε server staff. Για αυτό υπάρχει το discord. Α και κάτι ακόμα, ο άνθρωπος μπορεί να έχει και δουλειές και γιαυτό να μην μπαίνει.
