### ISSUE TITLE
Νέες ιδέες για των server!!!!!

### ISSUE THREAD

**Issue by theothak** [greeksamp/Greek-Roleplay-Script#83]

**Comment by greeksamp-souvlaki** [comment]
Παρ' όλο που το έκλεισες, αναφέρω απλά ότι το σύστημα έχει τροποποιηθεί με το νέο update.

Μόλις το δοκιμάσεις πάλι στο κινητό και αντιμετωπίσεις πρόβλημα, άνοιξε νέο issue να το ξανά δούμε, γιατί όντως στοχεύουμε και σε παίκτες από κινητό πλέον.
