### ISSUE TITLE
Bank /Transfer History

### ISSUE THREAD

**Issue by Storiel008** [greeksamp/Greek-Roleplay-Script#84]
Αυτό που λέει ο τίτλος. Όταν κάνουμε /transfer τα λεφτά μας σε κάποιον άλλον παίκτη, στην ιστοσελίδα του σέρβερ να έχει ένα μενού ο κάθε παίκτης στα στοιχεία λογαριασμού του που να δείχνει πότε έκανε /transfer, πόσα έκανε /transfer, και σε ποιόν έκανε /transfer. (Ουσιαστικά ένα πλαίσιο με όλα τα /transfer που έχει κάνει κάποιος)

Θα ήταν ωραίο να λειτουργούσε κάπως έτσι και το /pay αλλά εφόσον είναι limited στα 4000$ δεν είναι και τόσο αναγκαίο.

**Comment by greeksamp-souvlaki** [comment]
Ωραία η ιδέα!

Έχει υλοποιηθεί ήδη στο επόμενο update, με μία σελίδα που θα δείχνει όλες τις χρηματικές συναλλαγές του παίκτη.
