### ISSUE TITLE
F4 - Returning to class selection after next death - BUG

### ISSUE THREAD

**Issue by Storiel008** [greeksamp/Greek-Roleplay-Script#85]
Βρήκα ένα bug που για να συμβεί πρέπει επίτιδες να το προσπαθήσει ο παίκτης, αλλά δεν παύει να είναι ένα bug. Αν κάποιος πατήσει F4 ενώ παίζει, μόλις πεθάνει για τον οποιονδήποτε λόγο το server σταματάει να ανταποκρίνεται σωστά (για τον συγκεκριμένο παίκτη μόνο) και για να φτιαχτεί χρειάζεται reconnect. 

Video Example:
https://www.youtube.com/watch?v=XX-5OK70Bd0

**Comment by greeksamp-souvlaki** [comment]
Καλό, ευχαριστώ.
Πρέπει να δοκιμαστεί και με το καινούργιο σύστημα.

**Comment by Storiel008** [comment]
Μπορώ κάπως να βοηθήσω στο Testing, αν και ήδη είναι εύκολο να κάνει ο καθένας το bug;
