### ISSUE TITLE
Quest Event/Feature

### ISSUE THREAD

**Issue by Thanasis358** [greeksamp/Greek-Roleplay-Script#86]
Προτείνω να μπεί σαν Event ή Feature για τους νέους players ένα quest που θα έχει αστεράκια ή άλλα αντικείμενα σκορπισμένα στο map και όταν κάποιος παίχτης πάρει ένα, να του δίνει score ή λεφτά.
(Παρόμοιο με το Quest που υπήρχε τον Απρίλιο του 2020)

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ, δεν ξέρω αν είναι βολικό μόνο για τους νέους παίκτες, φοβάμαι θα γίνει κατάχρηση.

Αλλά όταν μπει το νέο update, σαν γιορτή θα μπορούσε να επιστρέψει ένα quest.

**Comment by greeksamp-souvlaki** [comment]
Μπήκε ένα quest για το update.
