### ISSUE TITLE
Wrong Password - BUG

### ISSUE THREAD

**Issue by Storiel008** [greeksamp/Greek-Roleplay-Script#93]
Βρήκα ένα bug που συμβαίνει αν ένας παίκτης βάλει λάθος κωδικό στο Login Screen. Το dialog δείχνει κανονικά πως έβαλε λάθος κωδικό ο παίκτης αλλά συνεχίζει να φορτώνει το σέρβερ με αποτέλεσμα να spawnαρει ο πάικτης στην μέση του πουθενά με ένα αλεξίπτωτο, έχοντας ακόμα το Login Screen μπροστά του. 
(Αυτο φτιάχνεται απλά αν ξαναπατήσει το Dialog και γράψει τον κωδικό του σωστά)

Video Example:
https://www.youtube.com/watch?v=UfN3hborrEM

**Comment by Arcon3** [comment]
Μολις πηγα να το γραψω αλλα ο bug guy με προλαβε..

**Comment by Storiel008** [comment]
Θα το έγραφα καλύτερα έτσι κ αλλιώς <3

**Comment by greeksamp-souvlaki** [comment]
Ευχαριστώ!
Αλλά αυτό έχει γίνει συγκεκριμένα για τους παίκτες που προσπαθούν να συνδεθούν και δεν είναι συνδεδεμένοι ακόμη.

Είναι ασφαλές.
