### ISSUE TITLE
Κλειδωμα τον Biz

### ISSUE THREAD

**Issue by Arcon3** [greeksamp/Greek-Roleplay-Script#99]
Θα πρωτεινα να μπορουμε να κλειδωνουμε ενα biz Π.χ Burger shop κλπ ωστε να μην μπορει να μπει κανενας για τον οποιδηποτε λογο

**Comment by greeksamp-souvlaki** [comment]
Για ποιο λόγο να γίνει κάτι τέτοιο όμως; Ποιος θέλει να κλείσει την επιχείρησή του και να μην παίρνει λεφτά και να δυσκολέψει του παίχτες;

Αν το σκεφτείς κάπως διαφορετικά όμως, στείλε πάλι.
